# Generated by Django 3.1.4 on 2020-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0019_auto_20201210_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="languageversion",
            name="outdated_characters",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="languageversion",
            name="outdated_strings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="languageversion",
            name="outdated_words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="languageversion",
            name="translated_characters",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="languageversion",
            name="translated_strings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="languageversion",
            name="translated_words",
            field=models.IntegerField(default=0),
        ),
    ]
