# Generated by Django 3.1.5 on 2021-01-20 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0029_auto_20210119_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trstringtexthistory",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
