# Generated by Django 3.2.25 on 2026-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0031_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                help_text="ISO 639-1 or ISO 639-2 code",
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
