# Generated by Django 3.1.4 on 2020-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20201211_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_new_texts",
            field=models.BooleanField(
                default=True,
                verbose_name="Informi min retpoŝte, kiam estas novaj tekstoj por traduki",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_translation_request",
            field=models.BooleanField(
                default=True,
                verbose_name="Informi min retpoŝte, kiam iu petas rajton traduki projekton, kiun mi administras",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
