# Generated by Django 3.1.5 on 2021-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20201217_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_new_comments",
            field=models.BooleanField(
                default=True,
                verbose_name="Informi min retpoŝte, kiam iu respondis mian komenton",
            ),
        ),
    ]
