name: tradukejo

services:

  django:
    build:
      context: .
      target: development
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - .:/app:z
      - ./.venv:/app/.venv:z
    working_dir: /app
    env_file:
      - .env
    user: ${USER_ID-1000}:${GROUP_ID-1000}
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py loaddata languages.json &&
      python manage.py compilemessages -v0 &&
      python manage.py runserver 0.0.0.0:${DJANGO_PORT}
      "
    networks:
      - backend
      - public
    ports:
      - $DJANGO_PORT:$DJANGO_PORT
    restart: always
    stop_grace_period: 2s

  vue:
    image: node:22.23-slim
    depends_on:
      - caddy
    working_dir: /app/vue-translation-interface
    user: ${USER_ID-1000}:${USER_ID-1000}
    volumes:
      - .:/app:z
    command: /bin/sh -c "npm i; npm run --verbose dev"
    tty: true
    networks:
      - backend

  vue-build:
    image: node:16.20-slim
    working_dir: /app/vue-translation-interface
    user: ${USER_ID-1000}:${USER_ID-1000}
    volumes:
      - .:/app:z
    command: /bin/sh -c "npm i; npm run --verbose build"

  vue-build-watch:
    extends: vue-build
    profiles: ["exclude"]
    tty: true
    command: sh -c "npm install && npm run build-watch"

  mariadb: &mariadb
    image: mariadb:10.11.11
    restart: always
    environment: &mariadb_env
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    command: --wait-timeout=28800
    volumes:
      - .docker/mariadb_data:/var/lib/mysql:z
    networks:
      - backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 30s
      timeout: 2s
      retries: 3

  mariadb-test:
    <<: *mariadb
    environment:
      <<: *mariadb_env
      MARIADB_DATABASE: test_$MARIADB_DATABASE
    volumes:
      - MARIADB_TEST:/var/lib/mysql
    ports:
      - 3306:3306

  caddy:
    image: caddy:alpine
    user: $USER_ID:$GROUP_ID
    environment:
      - LOCAL_HOST=${LOCAL_HOST}
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:24678:24678
    volumes:
      - ./containers/volumes/caddy/data:/data:Z
      - ./containers/volumes/caddy/etc/caddy:/etc/caddy:Z
    networks:
      - public
      - backend


networks:
  backend:
  public:

volumes:
  MARIADB_TEST:
