from django.conf import settings
from traduko import models


def settings_context(request):
    return {
        'WEBSITE_NAME': settings.WEBSITE_NAME,
        'DEFAULT_FROM_EMAIL': settings.DEFAULT_FROM_EMAIL,
        'TRANSLATION_STATE_TRANSLATED': models.TRANSLATION_STATE_TRANSLATED,
        'TRANSLATION_STATE_UNTRANSLATED': models.TRANSLATION_STATE_UNTRANSLATED,
        'TRANSLATION_STATE_OUTDATED': models.TRANSLATION_STATE_OUTDATED,
        'STATE_FILTER_ALL': models.STATE_FILTER_ALL,
        'STATE_FILTER_UNTRANSLATED': models.STATE_FILTER_UNTRANSLATED,
        'STATE_FILTER_OUTDATED': models.STATE_FILTER_OUTDATED,
        'STATE_FILTER_OUTDATED_UNTRANSLATED': models.STATE_FILTER_OUTDATED_UNTRANSLATED,
        'SORT_STRINGS_BY_NAME': models.SORT_STRINGS_BY_NAME,
        'SORT_STRINGS_BY_NEWEST': models.SORT_STRINGS_BY_NEWEST,
        'SORT_STRINGS_BY_OLDEST': models.SORT_STRINGS_BY_OLDEST,
    }
