# Generated by Django 3.2.25 on 2026-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20210318_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_language",
            field=models.CharField(
                choices=[
                    ("ca", "Català"),
                    ("cs", "Česky"),
                    ("en", "English"),
                    ("eo", "Esperanto"),
                    ("fi", "Suomi"),
                    ("fr", "Français"),
                    ("it", "Italiano"),
                    ("ms", "Bahasa Melayu"),
                    ("nl", "Nederlands"),
                    ("pl", "Polski"),
                    ("pt", "Português"),
                    ("sk", "Slovenčina"),
                ],
                default="eo",
                max_length=8,
                verbose_name="settings#email-language",
            ),
        ),
    ]
