# Generated by Django 4.2.30 on 2026-06-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_email_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeeplAuthKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Ekzemple: a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6:fx",
                        max_length=50,
                        unique=True,
                        validators=[users.models.deepl_api_key],
                        verbose_name="API key",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("dev", "Developer"),
                            ("grow", "Growth"),
                            ("entr", "Entreprise"),
                        ],
                        default="free",
                        max_length=4,
                    ),
                ),
                (
                    "character_count",
                    models.IntegerField(default=0, verbose_name="Character count"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DeepL Auth key",
                "verbose_name_plural": "DeepL Auth keys",
            },
        ),
    ]
