/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddString: typeof import('./src/components/translation/AddString.vue')['default']
    CommentsList: typeof import('./src/components/translation/bottom/CommentsList.vue')['default']
    DeletedString: typeof import('./src/components/translation/DeletedString.vue')['default']
    DirectoriesList: typeof import('./src/components/DirectoriesList.vue')['default']
    DirectoriesTree: typeof import('./src/components/DirectoriesTree.vue')['default']
    DirectoryNode: typeof import('./src/components/DirectoryNode.vue')['default']
    DisplayText: typeof import('./src/components/translation/DisplayText.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    LanguageChangeDropdown: typeof import('./src/components/translation/translatingFrom/LanguageChangeDropdown.vue')['default']
    LoadingButton: typeof import('./src/components/ui/LoadingButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    LoadMoreStrings: typeof import('./src/components/translation/LoadMoreStrings.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    OnlineTranslatorLinks: typeof import('./src/components/translation/translatingFrom/OnlineTranslatorLinks.vue')['default']
    ProposedTranslations: typeof import('./src/components/translation/translatingTo/ProposedTranslations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringComment: typeof import('./src/components/translation/bottom/StringComment.vue')['default']
    StringHistory: typeof import('./src/components/translation/bottom/StringHistory.vue')['default']
    StringInfo: typeof import('./src/components/translation/bottom/StringInfo.vue')['default']
    TextFrom: typeof import('./src/components/translation/translatingFrom/TextFrom.vue')['default']
    TextTo: typeof import('./src/components/translation/translatingTo/TextTo.vue')['default']
    TranslateForm: typeof import('./src/components/translation/translatingTo/TranslateForm.vue')['default']
    TranslationRow: typeof import('./src/components/translation/TranslationRow.vue')['default']
    TranslationRowHeader: typeof import('./src/components/translation/TranslationRowHeader.vue')['default']
    TranslationZone: typeof import('./src/components/translation/TranslationZone.vue')['default']
  }
}
