BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX
XXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXX XXX XX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXX XX XX XXXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBXXXXXXX XXXXXXXXXXXX
XXXXXXX

BBBBBBBB