BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBXXXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
	XXXXX
XXXXXX
XXXXX XX XXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXX XX XXX XXX XX XXXXXX XX XX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX

BBBBBBBB