BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX XXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBXXXXX XXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
	XXXXX
XXXXXX
BB BBBBBBBBB
XXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XXXXXXX XXXX XX XXXXX XXXXXXXX XX XX XXXXX XXXXXX XXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
	XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX
XXXXXXX
BBBB
XXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXX XX XXX XXXXX XXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
BBBBB
BBBBBBBB