BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX XXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBXXXXX XXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
	XXXXX
XXXXXX
XXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXX XXXXXXX XXX XXXXXXXX XX XX XXXXXX XXX XXXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX

BBBBBBBB