BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXXXXXBBBBBBBB
BBBBB BBBBBBBBBXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXXX
XXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX
BBBBBBBB