# Generated by Django 3.1.3 on 2020-11-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traduko', '0002_auto_20201104_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='Path of the string, can contain slashes for subfolders', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('pluralized', models.BooleanField(default=False)),
                ('words', models.IntegerField(default=0)),
                ('characters', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traduko.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrStringText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(1, 'Translated'), (0, 'Untranslated'), (2, 'Outdated')], default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traduko.language')),
                ('translated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trstring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traduko.trstring')),
            ],
        ),
    ]
