# Generated by Django 3.1.3 on 2020-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0004_languageversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageversion',
            options={'ordering': ['language']},
        ),
        migrations.AddField(
            model_name='trstring',
            name='context',
            field=models.TextField(blank=True, help_text='Short explanation for translators'),
        ),
    ]
