# Generated by Django 3.1.3 on 2020-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0007_auto_20201118_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trstringtext",
            name="last_change",
            field=models.DateTimeField(),
        ),
    ]
