# Generated by Django 3.1.3 on 2020-11-19 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traduko', '0008_auto_20201119_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languageversion',
            name='translator_requests',
            field=models.ManyToManyField(blank=True, related_name='translator_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languageversion',
            name='translators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
