# Generated by Django 3.1.3 on 2020-11-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traduko', '0009_auto_20201119_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageversion',
            name='translator_requests',
        ),
        migrations.CreateModel(
            name='TranslatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.TextField()),
                ('language_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traduko.languageversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
