# Generated by Django 3.1.3 on 2020-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0011_auto_20201125_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trstringtext',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
