# Generated by Django 3.1.3 on 2020-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0012_auto_20201125_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='trstring',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
