# Generated by Django 3.1.3 on 2020-11-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0013_trstring_last_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trstring',
            name='pluralized',
        ),
    ]
