# Generated by Django 3.1.4 on 2020-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0016_auto_20201127_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code']},
        ),
    ]
