# Generated by Django 3.1.4 on 2020-12-10 13:38

from django.db import migrations, models
import traduko.models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0018_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=traduko.models.project_image_upload_location
            ),
        ),
    ]
