# Generated by Django 3.1.4 on 2021-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduko', '0023_stringactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringactivity',
            name='action',
            field=models.CharField(choices=[('trans', 'translated'), ('edit', 'edited'), ('add', 'added'), ('imp', 'imported')], max_length=5),
        ),
    ]
