# Generated by Django 3.1.4 on 2021-01-05 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0026_auto_20210104_1316"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="plural_examples",
        ),
    ]
