# Generated by Django 3.1.5 on 2021-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traduko", "0027_remove_language_plural_examples"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trstringtext",
            unique_together={("trstring", "language")},
        ),
        migrations.AddIndex(
            model_name="trstringtext",
            index=models.Index(
                fields=["trstring", "language"], name="traduko_trs_trstrin_d7bc31_idx"
            ),
        ),
    ]
